### ISSUE TITLE
Does spotify-tui support env variables in its client.yml?

### ISSUE THREAD

**Issue by JohnCarterGonzalez** [Rigellute/spotify-tui#1092]
I have my .config/spotify-tui/client.yml file like:
```yaml
   client_id: ${SPT_CLIENT_ID}
   client_secret: ${SPT_CLIENT_SECRET}
   device_id: ${SPT_DEVICE_ID}
   port: 8888
```
which references the env variables of spotify api. The main reason I am using env variables, is for commiting my config files. Is there a step I am missing? When I run: `echo $SPT_CLIENT_ID` in the shell, the output is as expected. Yet when I run `spt`, it returns "INVALID CLIENT". Any help would be appreciated, thanks!
