### ISSUE TITLE
Implement a configuration file (e.g. for keybindings, etc.)

### ISSUE THREAD

**Issue by jfaltis** [Rigellute/spotify-tui#46]
Create a config for easy customization of keybindings, program behaviour, etc. It could be located at `$HOME/.config/spotify-tui/config.yml.`

The current client configurations could be moved into this configuration too.
E.g

```
---
client:
  - client_id:
  - client_secret:
  - device_id:
  
keybindings:
  - left: h
  - down: j
  - up: k
  - right: l
```
