### ISSUE TITLE
Cannot save songs

### ISSUE THREAD

**Issue by Babbie** [Rigellute/spotify-tui#495]
Whenever I try to press the hotkey for saving the currently highlighted song in the table, nothing happens. I have not altered the key in my config.yml, so ```s``` should still be assigned to it. My config.yml, just to be sure:
```
# Sample config file

# The theme colours can be an rgb string of the form "255, 255, 255" or a string that references the colours from your terminal theme: Reset, Black, Red, Green, Yellow, Blue, Magenta, Cyan, Gray, DarkGray, LightRed, LightGreen, LightYellow, LightBlue, LightMagenta, LightCyan, White.
theme:
  active: Cyan
  banner: LightCyan
  error_border: Red
  error_text: LightRed
  hint: Yellow
  hovered: Magenta
  inactive: Gray
  playbar_background: Black
  playbar_progress: LightCyan
  playbar_text: White
  selected: LightCyan
  text: White

behavior:
  seek_milliseconds: 5000
  volume_increment: 10
  # The lower the number the higher the "frames per second". You can decrease this number so that the audio visualisation is smoother but this can be expensive!
  tick_rate_milliseconds: 250

keybindings:
  # Key stroke can be used if it only uses two keys:
  # ctrl-q works,
  # ctrl-alt-q doesn't.
  back: "esc"

  jump_to_album: "a"

  # Shift modifiers use a capital letter (also applies with other modifier keys
  # like ctrl-A)
  jump_to_artist_album: "A"

  manage_devices: "d"
  decrease_volume: "-"
  increase_volume: "+"
  toggle_playback: " "
  seek_backwards: ","
  seek_forwards: "."
  next_track: ">"
  previous_track: "<"
  copy_song_url: "c"
  copy_album_url: "C"
  help: "?"
  repeat: "r"
  search: "/"
  audio_analysis: "v"
```
