### ISSUE TITLE
Style progressbar

### ISSUE THREAD

**Issue by mathiasrw** [Rigellute/spotify-tui#656]
Absolutly love it. Thank you. 

Is there a way of styling the progress bar? At the moment the bright colors combined with the chunky movement are a bit loud visually. Would love to adjust it to dark gray. 

![image](https://user-images.githubusercontent.com/1063454/98884441-4c5d3700-2490-11eb-9e9e-41d33b6153d5.png)

**Comment by OrangeFran** [comment]
You can actually tweak the polybar.
I found this in the README:
```
theme:
  active: Cyan # current playing song in list
  banner: LightCyan # the "spotify-tui" banner on launch
  error_border: Red # error dialog border
  error_text: LightRed # error message text (e.g. "Spotify API reported error 404")
  hint: Yellow # hint text in errors
  hovered: Magenta # hovered pane border
  inactive: Gray # borders of inactive panes
  playbar_background: Black # background of progress bar
  playbar_progress: LightCyan # filled-in part of the progress bar
  playbar_text: White # artist name in player pane
  selected: LightCyan # a) selected pane border, b) hovered item in list, & c) track title in player
  text: "255, 255, 255" # text in panes
  header: White # header text in panes (e.g. 'Title', 'Artist', etc.)
```
You're probably looking for the `playbar_progress` item.
