### ISSUE TITLE
Custom config causes broken rendering

### ISSUE THREAD

**Issue by warm-considering** [Rigellute/spotify-tui#663]
I manually changed the colours in the config to match the rest of my programs, however, the changes didn't seem to work, all text and borders appear white and there are some sort of blocky grey visual artifacts appearing in the empty spaces in the UI. Here is the config used:   
```
theme:
  active: "205,65,53" # current playing song in list
  banner: "170,221,238" # the "spotify-tui" banner on launch
  error_border: "255,0,0" # error dialog border
  error_text: "255,0,0" # error message text (e.g. "Spotify API reported error 404")
  hint: "0,100,100" # hint text in errors
  hovered: "205,65,53" # hovered pane border
  inactive: "170,221,238" # borders of inactive panes
  playbar_background: "0,0,0" # background of progress bar
  playbar_progress: "205,65,53" # filled-in part of the progress bar
  playbar_text: "170,221,238" # artist name in player pane
  selected: "205,65,53" # a) selected pane border, b) hovered item in list, & c) track title in player
  text: "170,221,238" # text in panes
  header: "255,255,255" # header text in panes (e.g. 'Title', 'Artist', etc.)

behavior:
  seek_milliseconds: 5000
  volume_increment: 10
  # The lower the number the higher the "frames per second". You can decrease this number so that the audio visualisation is smoother but this can be expensive!
  tick_rate_milliseconds: 250
  # Enable text emphasis (typically italic/bold text styling). Disabling this might be important if the terminal config is otherwise restricted and rendering text escapes interferes with the UI.
  enable_text_emphasis: false
  # controls whether to show a loading indicator in the top right of the UI whenever communicating with Spotify API
  show_loading_indicator: true
```
