### ISSUE TITLE
changing seek_milliseconds option seemingly not working

### ISSUE THREAD

**Issue by sandersantema** [Rigellute/spotify-tui#715]
I've got the following in my `config.yml` :
```yaml
behaviour:
  seek_milliseconds: 30000
```

But the seek duration is still 5 seconds. The custom keybindings I've set do work, so at least my config isn't in the wrong location. This is my complete `config.yml`:
```yaml
behaviour:
  seek_milliseconds: 30000

keybindings:
  next_page: "ctrl-]"
  revious_page: "ctlr-["
  jump_to_start: "g"
  jump_to_end: "G"

  seek_backwards: "s"
  seek_forwards: "d"

  shuffle: "ctrl-s"
  manage_devices: "ctrl-D"
```

I'm running `spotify-tui 0.23.0` and `spotify-d 0.3.0` (although I've built from source).
